[package]
name = "spider"
version = "1.0.0"
edition = "2024"

[[bin]]
name = "spider"
path = "src/spider/main.rs"

[[bin]]
name = "crawler"
path = "src/crawler/main.rs"

[lib]
name = "spider_shared"
path = "src/lib.rs"

[dependencies]
tokio.workspace = true
crossterm.workspace = true
url.workspace = true
rand.workspace = true
rand_distr.workspace = true
sqlx.workspace = true
reqwest.workspace = true
serde.workspace = true
rust-stemmers.workspace = true
scraper = "0.27.0"
shared = {path="../shared"}
